#!/bin/bash

if ! command -v "cargo-make" >/dev/null 2>&1; then
  echo "❌ cargo-make is required for pre-commit checks."
  cargo install --force cargo-make
fi

if ! command -v corepack >/dev/null 2>&1; then
  echo "❌ corepack is required for pre-commit checks."
  exit 1
fi

cargo make pre-commit
